version: '3.9'  

services:
  strapi:
    container_name: strapi
    image: ahblublu/bwm-sms-strap:v1.0
    restart: always
    env_file:
      .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}

    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/upload
    
    depends_on:
      - strapi_DB

    ports:
      - 1337:1337
    networks:
      - strapi

  strapi_DB:
    container_name: strapiDB
    image: postgres:latest
    restart: always
    volumes:
      - strapi-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=!QAZ#EDC5tgb7ujm
      - POSTGRES_USER=postuser1
      - POSTGRES_DB=strapiDB
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    driver: bridge