# fly.toml app configuration file generated for bwm-sms-strapi on 2024-10-28T23:01:48+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bwm-sms-strapi'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[services]]
  protocol = 'tcp'
  internal_port = 1337

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
