# fly.toml app configuration file generated for bwm-sms-backend on 2024-10-21T22:43:12+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bwm-sms-backend'
primary_region = 'sin'

[build]

[[mounts]]
  source = 'bwm_sms_db'
  destination = '/var/lib/postgresql/data'

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
