# 
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bwm-sms-strapi'
primary_region = 'sin'

[build]

[[services]]
  internal_port = 1337
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443


[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
